//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DldvServiceReference
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/exceptions/1.0")]
    public partial class ExceptionType
    {

        private ProgramException[] programExceptionsField;

        private ContolDataType controlDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        public ProgramException[] ProgramExceptions
        {
            get
            {
                return this.programExceptionsField;
            }
            set
            {
                this.programExceptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", IsNullable = true, Order = 1)]
        public ContolDataType ControlData
        {
            get
            {
                return this.controlDataField;
            }
            set
            {
                this.controlDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/exceptions/1.0")]
    public partial class ProgramException
    {

        private string exceptionIdField;

        private string exceptionTextField;

        private string exceptionTypeCodeField;

        private bool exceptionFatalIndicatorCodeField;

        private string exceptionCategoryCodeField;

        private ProgramExceptionElementType exceptionElementField;

        private string exceptionObjectTextField;

        private string exceptionActorTextField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ExceptionId
        {
            get
            {
                return this.exceptionIdField;
            }
            set
            {
                this.exceptionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ExceptionText
        {
            get
            {
                return this.exceptionTextField;
            }
            set
            {
                this.exceptionTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ExceptionTypeCode
        {
            get
            {
                return this.exceptionTypeCodeField;
            }
            set
            {
                this.exceptionTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool ExceptionFatalIndicatorCode
        {
            get
            {
                return this.exceptionFatalIndicatorCodeField;
            }
            set
            {
                this.exceptionFatalIndicatorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ExceptionCategoryCode
        {
            get
            {
                return this.exceptionCategoryCodeField;
            }
            set
            {
                this.exceptionCategoryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public ProgramExceptionElementType ExceptionElement
        {
            get
            {
                return this.exceptionElementField;
            }
            set
            {
                this.exceptionElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string ExceptionObjectText
        {
            get
            {
                return this.exceptionObjectTextField;
            }
            set
            {
                this.exceptionObjectTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string ExceptionActorText
        {
            get
            {
                return this.exceptionActorTextField;
            }
            set
            {
                this.exceptionActorTextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/exceptions/1.0")]
    public partial class ProgramExceptionElementType
    {

        private string exceptionElementTextField;

        private int exceptionElementOccurrenceIdField;

        private bool exceptionElementOccurrenceIdFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ExceptionElementText
        {
            get
            {
                return this.exceptionElementTextField;
            }
            set
            {
                this.exceptionElementTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int ExceptionElementOccurrenceId
        {
            get
            {
                return this.exceptionElementOccurrenceIdField;
            }
            set
            {
                this.exceptionElementOccurrenceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionElementOccurrenceIdSpecified
        {
            get
            {
                return this.exceptionElementOccurrenceIdFieldSpecified;
            }
            set
            {
                this.exceptionElementOccurrenceIdFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/usps_states/2.0")]
    public partial class UsStateCodeType
    {

        private UsStateCodeSimpleType valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public UsStateCodeSimpleType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/usps_states/2.0")]
    public enum UsStateCodeSimpleType
    {

        /// <remarks/>
        AA,

        /// <remarks/>
        AE,

        /// <remarks/>
        AK,

        /// <remarks/>
        AL,

        /// <remarks/>
        AP,

        /// <remarks/>
        AR,

        /// <remarks/>
        AS,

        /// <remarks/>
        AZ,

        /// <remarks/>
        CA,

        /// <remarks/>
        CO,

        /// <remarks/>
        CT,

        /// <remarks/>
        DC,

        /// <remarks/>
        DE,

        /// <remarks/>
        FL,

        /// <remarks/>
        FM,

        /// <remarks/>
        GA,

        /// <remarks/>
        GU,

        /// <remarks/>
        HI,

        /// <remarks/>
        IA,

        /// <remarks/>
        ID,

        /// <remarks/>
        IL,

        /// <remarks/>
        IN,

        /// <remarks/>
        KS,

        /// <remarks/>
        KY,

        /// <remarks/>
        LA,

        /// <remarks/>
        MA,

        /// <remarks/>
        MD,

        /// <remarks/>
        ME,

        /// <remarks/>
        MH,

        /// <remarks/>
        MI,

        /// <remarks/>
        MN,

        /// <remarks/>
        MO,

        /// <remarks/>
        MP,

        /// <remarks/>
        MS,

        /// <remarks/>
        MT,

        /// <remarks/>
        NC,

        /// <remarks/>
        ND,

        /// <remarks/>
        NE,

        /// <remarks/>
        NH,

        /// <remarks/>
        NJ,

        /// <remarks/>
        NM,

        /// <remarks/>
        NV,

        /// <remarks/>
        NY,

        /// <remarks/>
        OH,

        /// <remarks/>
        OK,

        /// <remarks/>
        OR,

        /// <remarks/>
        PA,

        /// <remarks/>
        PR,

        /// <remarks/>
        PW,

        /// <remarks/>
        RI,

        /// <remarks/>
        SC,

        /// <remarks/>
        SD,

        /// <remarks/>
        TN,

        /// <remarks/>
        TX,

        /// <remarks/>
        UT,

        /// <remarks/>
        VA,

        /// <remarks/>
        VI,

        /// <remarks/>
        VT,

        /// <remarks/>
        WA,

        /// <remarks/>
        WI,

        /// <remarks/>
        WV,

        /// <remarks/>
        WY,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/proxy/xsd/2.0")]
    public partial class integer
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public partial class PersonEyeColorCodeType
    {

        private PersonEyeColorCodeSimpleType valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public PersonEyeColorCodeSimpleType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public enum PersonEyeColorCodeSimpleType
    {

        /// <remarks/>
        BLK,

        /// <remarks/>
        BLU,

        /// <remarks/>
        BRO,

        /// <remarks/>
        GRY,

        /// <remarks/>
        GRN,

        /// <remarks/>
        HAZ,

        /// <remarks/>
        MAR,

        /// <remarks/>
        PNK,

        /// <remarks/>
        DIC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public partial class PersonSexCodeType
    {

        private PersonSexCodeSimpleType valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public PersonSexCodeSimpleType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public enum PersonSexCodeSimpleType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public partial class DocumentCategoryCodeType
    {

        private DocumentCategoryCodeSimpleType valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public DocumentCategoryCodeSimpleType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public enum DocumentCategoryCodeSimpleType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/proxy/xsd/2.0")]
    public partial class date
    {

        private System.DateTime valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProperNameTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameTextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/proxy/xsd/2.0")]
    public partial class @string
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProperNameTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameTextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0")]
    public partial class TextType : @string
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameTextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0")]
    public partial class ProperNameTextType : TextType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0")]
    public partial class PersonNameTextType : ProperNameTextType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyDriverLicenseDataResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageAddressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContolDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyDriverLicenseDataRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/structures/2.0")]
    public abstract partial class ComplexObjectType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/dldv/dldverification/2.1")]
    public partial class VerifyDriverLicenseDataResponseType : ComplexObjectType
    {

        private ContolDataType controlDataField;

        private bool driverLicenseNumberMatchIndicatorField;

        private bool personBirthDateMatchIndicatorField;

        private bool personBirthDateMatchIndicatorFieldSpecified;

        private bool personLastNameExactMatchIndicatorField;

        private bool personLastNameExactMatchIndicatorFieldSpecified;

        private bool personLastNameFuzzyPrimaryMatchIndicatorField;

        private bool personLastNameFuzzyPrimaryMatchIndicatorFieldSpecified;

        private bool personLastNameFuzzyAlternateMatchIndicatorField;

        private bool personLastNameFuzzyAlternateMatchIndicatorFieldSpecified;

        private bool personFirstNameExactMatchIndicatorField;

        private bool personFirstNameExactMatchIndicatorFieldSpecified;

        private bool personFirstNameFuzzyPrimaryMatchIndicatorField;

        private bool personFirstNameFuzzyPrimaryMatchIndicatorFieldSpecified;

        private bool personFirstNameFuzzyAlternateMatchIndicatorField;

        private bool personFirstNameFuzzyAlternateMatchIndicatorFieldSpecified;

        private bool personMiddleNameExactMatchIndicatorField;

        private bool personMiddleNameExactMatchIndicatorFieldSpecified;

        private bool personMiddleNameFuzzyPrimaryMatchIndicatorField;

        private bool personMiddleNameFuzzyPrimaryMatchIndicatorFieldSpecified;

        private bool personMiddleNameFuzzyAlternateMatchIndicatorField;

        private bool personMiddleNameFuzzyAlternateMatchIndicatorFieldSpecified;

        private bool personMiddleInitialMatchIndicatorField;

        private bool personMiddleInitialMatchIndicatorFieldSpecified;

        private bool personNameSuffixMatchIndicatorField;

        private bool personNameSuffixMatchIndicatorFieldSpecified;

        private bool documentCategoryMatchIndicatorField;

        private bool documentCategoryMatchIndicatorFieldSpecified;

        private bool driverLicenseIssueDateMatchIndicatorField;

        private bool driverLicenseIssueDateMatchIndicatorFieldSpecified;

        private bool driverLicenseExpirationDateMatchIndicatorField;

        private bool driverLicenseExpirationDateMatchIndicatorFieldSpecified;

        private bool personSexCodeMatchIndicatorField;

        private bool personSexCodeMatchIndicatorFieldSpecified;

        private bool personHeightMatchIndicatorField;

        private bool personHeightMatchIndicatorFieldSpecified;

        private bool personWeightMatchIndicatorField;

        private bool personWeightMatchIndicatorFieldSpecified;

        private bool personEyeColorMatchIndicatorField;

        private bool personEyeColorMatchIndicatorFieldSpecified;

        private bool addressLine1MatchIndicatorField;

        private bool addressLine1MatchIndicatorFieldSpecified;

        private bool addressLine2MatchIndicatorField;

        private bool addressLine2MatchIndicatorFieldSpecified;

        private bool addressCityMatchIndicatorField;

        private bool addressCityMatchIndicatorFieldSpecified;

        private bool addressStateCodeMatchIndicatorField;

        private bool addressStateCodeMatchIndicatorFieldSpecified;

        private bool addressZIP5MatchIndicatorField;

        private bool addressZIP5MatchIndicatorFieldSpecified;

        private bool addressZIP4MatchIndicatorField;

        private bool addressZIP4MatchIndicatorFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", IsNullable = true, Order = 0)]
        public ContolDataType ControlData
        {
            get
            {
                return this.controlDataField;
            }
            set
            {
                this.controlDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 1)]
        public bool DriverLicenseNumberMatchIndicator
        {
            get
            {
                return this.driverLicenseNumberMatchIndicatorField;
            }
            set
            {
                this.driverLicenseNumberMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 2)]
        public bool PersonBirthDateMatchIndicator
        {
            get
            {
                return this.personBirthDateMatchIndicatorField;
            }
            set
            {
                this.personBirthDateMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonBirthDateMatchIndicatorSpecified
        {
            get
            {
                return this.personBirthDateMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personBirthDateMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 3)]
        public bool PersonLastNameExactMatchIndicator
        {
            get
            {
                return this.personLastNameExactMatchIndicatorField;
            }
            set
            {
                this.personLastNameExactMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonLastNameExactMatchIndicatorSpecified
        {
            get
            {
                return this.personLastNameExactMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personLastNameExactMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 4)]
        public bool PersonLastNameFuzzyPrimaryMatchIndicator
        {
            get
            {
                return this.personLastNameFuzzyPrimaryMatchIndicatorField;
            }
            set
            {
                this.personLastNameFuzzyPrimaryMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonLastNameFuzzyPrimaryMatchIndicatorSpecified
        {
            get
            {
                return this.personLastNameFuzzyPrimaryMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personLastNameFuzzyPrimaryMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 5)]
        public bool PersonLastNameFuzzyAlternateMatchIndicator
        {
            get
            {
                return this.personLastNameFuzzyAlternateMatchIndicatorField;
            }
            set
            {
                this.personLastNameFuzzyAlternateMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonLastNameFuzzyAlternateMatchIndicatorSpecified
        {
            get
            {
                return this.personLastNameFuzzyAlternateMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personLastNameFuzzyAlternateMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 6)]
        public bool PersonFirstNameExactMatchIndicator
        {
            get
            {
                return this.personFirstNameExactMatchIndicatorField;
            }
            set
            {
                this.personFirstNameExactMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonFirstNameExactMatchIndicatorSpecified
        {
            get
            {
                return this.personFirstNameExactMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personFirstNameExactMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 7)]
        public bool PersonFirstNameFuzzyPrimaryMatchIndicator
        {
            get
            {
                return this.personFirstNameFuzzyPrimaryMatchIndicatorField;
            }
            set
            {
                this.personFirstNameFuzzyPrimaryMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonFirstNameFuzzyPrimaryMatchIndicatorSpecified
        {
            get
            {
                return this.personFirstNameFuzzyPrimaryMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personFirstNameFuzzyPrimaryMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 8)]
        public bool PersonFirstNameFuzzyAlternateMatchIndicator
        {
            get
            {
                return this.personFirstNameFuzzyAlternateMatchIndicatorField;
            }
            set
            {
                this.personFirstNameFuzzyAlternateMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonFirstNameFuzzyAlternateMatchIndicatorSpecified
        {
            get
            {
                return this.personFirstNameFuzzyAlternateMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personFirstNameFuzzyAlternateMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 9)]
        public bool PersonMiddleNameExactMatchIndicator
        {
            get
            {
                return this.personMiddleNameExactMatchIndicatorField;
            }
            set
            {
                this.personMiddleNameExactMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonMiddleNameExactMatchIndicatorSpecified
        {
            get
            {
                return this.personMiddleNameExactMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personMiddleNameExactMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 10)]
        public bool PersonMiddleNameFuzzyPrimaryMatchIndicator
        {
            get
            {
                return this.personMiddleNameFuzzyPrimaryMatchIndicatorField;
            }
            set
            {
                this.personMiddleNameFuzzyPrimaryMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonMiddleNameFuzzyPrimaryMatchIndicatorSpecified
        {
            get
            {
                return this.personMiddleNameFuzzyPrimaryMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personMiddleNameFuzzyPrimaryMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 11)]
        public bool PersonMiddleNameFuzzyAlternateMatchIndicator
        {
            get
            {
                return this.personMiddleNameFuzzyAlternateMatchIndicatorField;
            }
            set
            {
                this.personMiddleNameFuzzyAlternateMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonMiddleNameFuzzyAlternateMatchIndicatorSpecified
        {
            get
            {
                return this.personMiddleNameFuzzyAlternateMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personMiddleNameFuzzyAlternateMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 12)]
        public bool PersonMiddleInitialMatchIndicator
        {
            get
            {
                return this.personMiddleInitialMatchIndicatorField;
            }
            set
            {
                this.personMiddleInitialMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonMiddleInitialMatchIndicatorSpecified
        {
            get
            {
                return this.personMiddleInitialMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personMiddleInitialMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 13)]
        public bool PersonNameSuffixMatchIndicator
        {
            get
            {
                return this.personNameSuffixMatchIndicatorField;
            }
            set
            {
                this.personNameSuffixMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonNameSuffixMatchIndicatorSpecified
        {
            get
            {
                return this.personNameSuffixMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personNameSuffixMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 14)]
        public bool DocumentCategoryMatchIndicator
        {
            get
            {
                return this.documentCategoryMatchIndicatorField;
            }
            set
            {
                this.documentCategoryMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentCategoryMatchIndicatorSpecified
        {
            get
            {
                return this.documentCategoryMatchIndicatorFieldSpecified;
            }
            set
            {
                this.documentCategoryMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 15)]
        public bool DriverLicenseIssueDateMatchIndicator
        {
            get
            {
                return this.driverLicenseIssueDateMatchIndicatorField;
            }
            set
            {
                this.driverLicenseIssueDateMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DriverLicenseIssueDateMatchIndicatorSpecified
        {
            get
            {
                return this.driverLicenseIssueDateMatchIndicatorFieldSpecified;
            }
            set
            {
                this.driverLicenseIssueDateMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 16)]
        public bool DriverLicenseExpirationDateMatchIndicator
        {
            get
            {
                return this.driverLicenseExpirationDateMatchIndicatorField;
            }
            set
            {
                this.driverLicenseExpirationDateMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DriverLicenseExpirationDateMatchIndicatorSpecified
        {
            get
            {
                return this.driverLicenseExpirationDateMatchIndicatorFieldSpecified;
            }
            set
            {
                this.driverLicenseExpirationDateMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 17)]
        public bool PersonSexCodeMatchIndicator
        {
            get
            {
                return this.personSexCodeMatchIndicatorField;
            }
            set
            {
                this.personSexCodeMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonSexCodeMatchIndicatorSpecified
        {
            get
            {
                return this.personSexCodeMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personSexCodeMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 18)]
        public bool PersonHeightMatchIndicator
        {
            get
            {
                return this.personHeightMatchIndicatorField;
            }
            set
            {
                this.personHeightMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonHeightMatchIndicatorSpecified
        {
            get
            {
                return this.personHeightMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personHeightMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 19)]
        public bool PersonWeightMatchIndicator
        {
            get
            {
                return this.personWeightMatchIndicatorField;
            }
            set
            {
                this.personWeightMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonWeightMatchIndicatorSpecified
        {
            get
            {
                return this.personWeightMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personWeightMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 20)]
        public bool PersonEyeColorMatchIndicator
        {
            get
            {
                return this.personEyeColorMatchIndicatorField;
            }
            set
            {
                this.personEyeColorMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonEyeColorMatchIndicatorSpecified
        {
            get
            {
                return this.personEyeColorMatchIndicatorFieldSpecified;
            }
            set
            {
                this.personEyeColorMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 21)]
        public bool AddressLine1MatchIndicator
        {
            get
            {
                return this.addressLine1MatchIndicatorField;
            }
            set
            {
                this.addressLine1MatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressLine1MatchIndicatorSpecified
        {
            get
            {
                return this.addressLine1MatchIndicatorFieldSpecified;
            }
            set
            {
                this.addressLine1MatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 22)]
        public bool AddressLine2MatchIndicator
        {
            get
            {
                return this.addressLine2MatchIndicatorField;
            }
            set
            {
                this.addressLine2MatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressLine2MatchIndicatorSpecified
        {
            get
            {
                return this.addressLine2MatchIndicatorFieldSpecified;
            }
            set
            {
                this.addressLine2MatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 23)]
        public bool AddressCityMatchIndicator
        {
            get
            {
                return this.addressCityMatchIndicatorField;
            }
            set
            {
                this.addressCityMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressCityMatchIndicatorSpecified
        {
            get
            {
                return this.addressCityMatchIndicatorFieldSpecified;
            }
            set
            {
                this.addressCityMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 24)]
        public bool AddressStateCodeMatchIndicator
        {
            get
            {
                return this.addressStateCodeMatchIndicatorField;
            }
            set
            {
                this.addressStateCodeMatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressStateCodeMatchIndicatorSpecified
        {
            get
            {
                return this.addressStateCodeMatchIndicatorFieldSpecified;
            }
            set
            {
                this.addressStateCodeMatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 25)]
        public bool AddressZIP5MatchIndicator
        {
            get
            {
                return this.addressZIP5MatchIndicatorField;
            }
            set
            {
                this.addressZIP5MatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressZIP5MatchIndicatorSpecified
        {
            get
            {
                return this.addressZIP5MatchIndicatorFieldSpecified;
            }
            set
            {
                this.addressZIP5MatchIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 26)]
        public bool AddressZIP4MatchIndicator
        {
            get
            {
                return this.addressZIP4MatchIndicatorField;
            }
            set
            {
                this.addressZIP4MatchIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressZIP4MatchIndicatorSpecified
        {
            get
            {
                return this.addressZIP4MatchIndicatorFieldSpecified;
            }
            set
            {
                this.addressZIP4MatchIndicatorFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public partial class ContolDataType : ComplexObjectType
    {

        private MessageAddressType messageAddressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public MessageAddressType MessageAddress
        {
            get
            {
                return this.messageAddressField;
            }
            set
            {
                this.messageAddressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public partial class MessageAddressType : ComplexObjectType
    {

        private TextType transactionLocatorIdField;

        private TextType messageOriginatorIdField;

        private TextType messageDestinationIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public TextType TransactionLocatorId
        {
            get
            {
                return this.transactionLocatorIdField;
            }
            set
            {
                this.transactionLocatorIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TextType MessageOriginatorId
        {
            get
            {
                return this.messageOriginatorIdField;
            }
            set
            {
                this.messageOriginatorIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public TextType MessageDestinationId
        {
            get
            {
                return this.messageDestinationIdField;
            }
            set
            {
                this.messageDestinationIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/niem/extensions/1.0")]
    public partial class AddressType : ComplexObjectType
    {

        private TextType[] addressDeliveryPointTextField;

        private ProperNameTextType locationCityNameField;

        private UsStateCodeType locationStateUsPostalServiceCodeField;

        private @string locationPostalCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressDeliveryPointText", Namespace = "http://niem.gov/niem/niem-core/2.0", Order = 0)]
        public TextType[] AddressDeliveryPointText
        {
            get
            {
                return this.addressDeliveryPointTextField;
            }
            set
            {
                this.addressDeliveryPointTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0", Order = 1)]
        public ProperNameTextType LocationCityName
        {
            get
            {
                return this.locationCityNameField;
            }
            set
            {
                this.locationCityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0", Order = 2)]
        public UsStateCodeType LocationStateUsPostalServiceCode
        {
            get
            {
                return this.locationStateUsPostalServiceCodeField;
            }
            set
            {
                this.locationStateUsPostalServiceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0", Order = 3)]
        public @string LocationPostalCode
        {
            get
            {
                return this.locationPostalCodeField;
            }
            set
            {
                this.locationPostalCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0")]
    public partial class PersonNameType : ComplexObjectType
    {

        private PersonNameTextType personGivenNameField;

        private PersonNameTextType personMiddleNameField;

        private PersonNameTextType personSurNameField;

        private TextType personNameSuffixTextField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PersonNameTextType PersonGivenName
        {
            get
            {
                return this.personGivenNameField;
            }
            set
            {
                this.personGivenNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PersonNameTextType PersonMiddleName
        {
            get
            {
                return this.personMiddleNameField;
            }
            set
            {
                this.personMiddleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public PersonNameTextType PersonSurName
        {
            get
            {
                return this.personSurNameField;
            }
            set
            {
                this.personSurNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public TextType PersonNameSuffixText
        {
            get
            {
                return this.personNameSuffixTextField;
            }
            set
            {
                this.personNameSuffixTextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0")]
    public partial class IdentificationType : ComplexObjectType
    {

        private @string identificationIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public @string IdentificationID
        {
            get
            {
                return this.identificationIDField;
            }
            set
            {
                this.identificationIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aamva.org/dldv/dldverification/2.1")]
    public partial class VerifyDriverLicenseDataRequestType : ComplexObjectType
    {

        private ContolDataType controlDataField;

        private IdentificationType driverLicenseIdentificationField;

        private date personBirthDateField;

        private PersonNameType personNameField;

        private date driverLicenseIssueDateField;

        private date driverLicenseExpirationDateField;

        private DocumentCategoryCodeType documentCategoryCodeField;

        private PersonSexCodeType personSexCodeField;

        private PersonEyeColorCodeType personEyeColorCodeField;

        private integer personHeightMeasureField;

        private integer personWeightMeasureField;

        private AddressType addressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", IsNullable = true, Order = 0)]
        public ContolDataType ControlData
        {
            get
            {
                return this.controlDataField;
            }
            set
            {
                this.controlDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0", IsNullable = true, Order = 1)]
        public IdentificationType DriverLicenseIdentification
        {
            get
            {
                return this.driverLicenseIdentificationField;
            }
            set
            {
                this.driverLicenseIdentificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 2)]
        public date PersonBirthDate
        {
            get
            {
                return this.personBirthDateField;
            }
            set
            {
                this.personBirthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/niem-core/2.0", Order = 3)]
        public PersonNameType PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 4)]
        public date DriverLicenseIssueDate
        {
            get
            {
                return this.driverLicenseIssueDateField;
            }
            set
            {
                this.driverLicenseIssueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 5)]
        public date DriverLicenseExpirationDate
        {
            get
            {
                return this.driverLicenseExpirationDateField;
            }
            set
            {
                this.driverLicenseExpirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 6)]
        public DocumentCategoryCodeType DocumentCategoryCode
        {
            get
            {
                return this.documentCategoryCodeField;
            }
            set
            {
                this.documentCategoryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 7)]
        public PersonSexCodeType PersonSexCode
        {
            get
            {
                return this.personSexCodeField;
            }
            set
            {
                this.personSexCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 8)]
        public PersonEyeColorCodeType PersonEyeColorCode
        {
            get
            {
                return this.personEyeColorCodeField;
            }
            set
            {
                this.personEyeColorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 9)]
        public integer PersonHeightMeasure
        {
            get
            {
                return this.personHeightMeasureField;
            }
            set
            {
                this.personHeightMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 10)]
        public integer PersonWeightMeasure
        {
            get
            {
                return this.personWeightMeasureField;
            }
            set
            {
                this.personWeightMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://aamva.org/niem/extensions/1.0", Order = 11)]
        public AddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://aamva.org/dldv/wsdl/2.1", ConfigurationName = "ServiceReference.IDLDVService21")]
    public interface IDLDVService21
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://aamva.org/dldv/wsdl/2.1/IDLDVService21/VerifyDriverLicenseData", ReplyAction = "http://aamva.org/dldv/wsdl/2.1/IDLDVService21/VerifyDriverLicenseDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DldvServiceReference.ExceptionType), Action = "http://aamva.org/dldv/wsdl/2.1/IDLDVService21/VerifyDriverLicenseDataExceptionTyp" +
            "eFault", Name = "Exception", Namespace = "http://aamva.org/exceptions/1.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComplexObjectType))]
        System.Threading.Tasks.Task<DldvServiceReference.VerifyDriverLicenseDataResponse> VerifyDriverLicenseDataAsync(DldvServiceReference.VerifyDriverLicenseDataRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "VerifyDriverLicenseData", WrapperNamespace = "http://aamva.org/dldv/wsdl/2.1", IsWrapped = true)]
    public partial class VerifyDriverLicenseDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://aamva.org/dldv/wsdl/2.1", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] token;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://aamva.org/dldv/wsdl/2.1", Order = 1)]
        public DldvServiceReference.VerifyDriverLicenseDataRequestType verifyDriverLicenseDataRequest;

        public VerifyDriverLicenseDataRequest()
        {
        }

        public VerifyDriverLicenseDataRequest(byte[] token, DldvServiceReference.VerifyDriverLicenseDataRequestType verifyDriverLicenseDataRequest)
        {
            this.token = token;
            this.verifyDriverLicenseDataRequest = verifyDriverLicenseDataRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "VerifyDriverLicenseDataResponse", WrapperNamespace = "http://aamva.org/dldv/wsdl/2.1", IsWrapped = true)]
    public partial class VerifyDriverLicenseDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://aamva.org/dldv/wsdl/2.1", Order = 0)]
        public DldvServiceReference.VerifyDriverLicenseDataResponseType VerifyDriverLicenseDataResult;

        public VerifyDriverLicenseDataResponse()
        {
        }

        public VerifyDriverLicenseDataResponse(DldvServiceReference.VerifyDriverLicenseDataResponseType VerifyDriverLicenseDataResult)
        {
            this.VerifyDriverLicenseDataResult = VerifyDriverLicenseDataResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IDLDVService21Channel : DldvServiceReference.IDLDVService21, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DLDVService21Client : System.ServiceModel.ClientBase<DldvServiceReference.IDLDVService21>, DldvServiceReference.IDLDVService21
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public DLDVService21Client() :
                base(DLDVService21Client.GetDefaultBinding(), DLDVService21Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IDLDVService21.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DLDVService21Client(EndpointConfiguration endpointConfiguration) :
                base(DLDVService21Client.GetBindingForEndpoint(endpointConfiguration), DLDVService21Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DLDVService21Client(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(DLDVService21Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DLDVService21Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(DLDVService21Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DLDVService21Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DldvServiceReference.VerifyDriverLicenseDataResponse> DldvServiceReference.IDLDVService21.VerifyDriverLicenseDataAsync(DldvServiceReference.VerifyDriverLicenseDataRequest request)
        {
            return base.Channel.VerifyDriverLicenseDataAsync(request);
        }

        public System.Threading.Tasks.Task<DldvServiceReference.VerifyDriverLicenseDataResponse> VerifyDriverLicenseDataAsync(byte[] token, DldvServiceReference.VerifyDriverLicenseDataRequestType verifyDriverLicenseDataRequest)
        {
            DldvServiceReference.VerifyDriverLicenseDataRequest inValue = new DldvServiceReference.VerifyDriverLicenseDataRequest();
            inValue.token = token;
            inValue.verifyDriverLicenseDataRequest = verifyDriverLicenseDataRequest;
            return ((DldvServiceReference.IDLDVService21)(this)).VerifyDriverLicenseDataAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IDLDVService21))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IDLDVService21))
            {
                return new System.ServiceModel.EndpointAddress("");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DLDVService21Client.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IDLDVService21);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DLDVService21Client.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IDLDVService21);
        }

        public enum EndpointConfiguration
        {
            WSHttpBinding_IDLDVService21,
        }
    }
}
